<!DOCTYPE html>
<html lang="de" xml:lang="de">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Methodik | PM2.5 Zeitreihenanalyse von den deutschen Landeshauptstädten</title>
  <meta name="description" content="3 Methodik | PM2.5 Zeitreihenanalyse von den deutschen Landeshauptstädten im Jahr 2023" />
  <meta name="generator" content="bookdown 0.38 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Methodik | PM2.5 Zeitreihenanalyse von den deutschen Landeshauptstädten" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="3 Methodik | PM2.5 Zeitreihenanalyse von den deutschen Landeshauptstädten im Jahr 2023" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Methodik | PM2.5 Zeitreihenanalyse von den deutschen Landeshauptstädten" />
  
  <meta name="twitter:description" content="3 Methodik | PM2.5 Zeitreihenanalyse von den deutschen Landeshauptstädten im Jahr 2023" />
  

<meta name="author" content="Patricia Schwarzkopf" />


<meta name="date" content="2024-03-31" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="einleitung.html"/>
<link rel="next" href="analyse.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Pm2,5</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> index</a></li>
<li class="chapter" data-level="2" data-path="einleitung.html"><a href="einleitung.html"><i class="fa fa-check"></i><b>2</b> Einleitung</a>
<ul>
<li class="chapter" data-level="2.1" data-path="einleitung.html"><a href="einleitung.html#hypothese-und-forschungsfrage"><i class="fa fa-check"></i><b>2.1</b> Hypothese und Forschungsfrage</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="methodik.html"><a href="methodik.html"><i class="fa fa-check"></i><b>3</b> Methodik</a>
<ul>
<li class="chapter" data-level="3.1" data-path="methodik.html"><a href="methodik.html#datenbeschaffung"><i class="fa fa-check"></i><b>3.1</b> Datenbeschaffung</a></li>
<li class="chapter" data-level="3.2" data-path="methodik.html"><a href="methodik.html#packages-und-working-directory"><i class="fa fa-check"></i><b>3.2</b> Packages und Working Directory</a></li>
<li class="chapter" data-level="3.3" data-path="methodik.html"><a href="methodik.html#datenbereinigung"><i class="fa fa-check"></i><b>3.3</b> Datenbereinigung</a></li>
<li class="chapter" data-level="3.4" data-path="methodik.html"><a href="methodik.html#datenüberprüfung-auf-vollständigkeit"><i class="fa fa-check"></i><b>3.4</b> Datenüberprüfung auf Vollständigkeit</a></li>
<li class="chapter" data-level="3.5" data-path="methodik.html"><a href="methodik.html#ermittlung-der-häufigsten-messzeiten-und-auswahl-des-analysezeitraums"><i class="fa fa-check"></i><b>3.5</b> Ermittlung der häufigsten Messzeiten und Auswahl des Analysezeitraums</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="analyse.html"><a href="analyse.html"><i class="fa fa-check"></i><b>4</b> Analyse</a>
<ul>
<li class="chapter" data-level="4.1" data-path="analyse.html"><a href="analyse.html#vorbereitung-der-datenimputation"><i class="fa fa-check"></i><b>4.1</b> Vorbereitung der Datenimputation</a></li>
<li class="chapter" data-level="4.2" data-path="analyse.html"><a href="analyse.html#datenimputation-und-analyse"><i class="fa fa-check"></i><b>4.2</b> Datenimputation und Analyse</a></li>
<li class="chapter" data-level="4.3" data-path="analyse.html"><a href="analyse.html#imputationverfahren"><i class="fa fa-check"></i><b>4.3</b> Imputationverfahren</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ergebnisse.html"><a href="ergebnisse.html"><i class="fa fa-check"></i><b>5</b> Ergebnisse</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ergebnisse.html"><a href="ergebnisse.html#geografische-darstellung-der-daten"><i class="fa fa-check"></i><b>5.1</b> Geografische Darstellung der Daten</a></li>
<li class="chapter" data-level="5.2" data-path="ergebnisse.html"><a href="ergebnisse.html#clusteranalyse-der-städte"><i class="fa fa-check"></i><b>5.2</b> Clusteranalyse der Städte</a></li>
<li class="chapter" data-level="5.3" data-path="ergebnisse.html"><a href="ergebnisse.html#saisonale-analyse"><i class="fa fa-check"></i><b>5.3</b> Saisonale Analyse</a></li>
<li class="chapter" data-level="5.4" data-path="ergebnisse.html"><a href="ergebnisse.html#schwellenwertüberschreitung"><i class="fa fa-check"></i><b>5.4</b> Schwellenwertüberschreitung</a></li>
<li class="chapter" data-level="5.5" data-path="ergebnisse.html"><a href="ergebnisse.html#detailanalyse"><i class="fa fa-check"></i><b>5.5</b> Detailanalyse</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="diskussion-und-reflektion.html"><a href="diskussion-und-reflektion.html"><i class="fa fa-check"></i><b>6</b> Diskussion und Reflektion</a></li>
<li class="chapter" data-level="7" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>7</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PM2.5 Zeitreihenanalyse von den deutschen Landeshauptstädten</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="methodik" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Methodik<a href="methodik.html#methodik" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="datenbeschaffung" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Datenbeschaffung<a href="methodik.html#datenbeschaffung" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Die in dieser Studie verwendeten Luftqualitätsdaten wurden von der Open-Source-Plattform <a href="https://openaq.org/">openaq Website</a> bezogen, die weltweit Luftqualitätsdaten sammelt und zur Verfügung stellt. Für diese Analyse wurden spezifische Daten aus den Messungen der PM<sub>2,5</sub>-Konzentrationen in µg/m³ verwendet, die von der EEA Germany bereitgestellt werden. Es wurden Daten aus 16 deutschen Landeshauptstädten ausgewählt, um ein breites Spektrum an geografischen Standorten und Umweltbedingungen abzudecken. Die Auswahl der Messstationen in den jeweiligen Städten erfolgte nach Verfügbarkeit von PM<sub>2,5</sub>-Daten für das Jahr 2023. Aufgrund unvollständiger Datensätze für bestimmte Zeiträume oder fehlender PM<sub>2,5</sub>-Messungen an einigen Stationen, war es notwendig, die Datenauswahl auf die Stationen zu beschränken, die den Anforderungen entsprachen. In Städten mit mehreren geeigneten Messstationen wurde eine Station zufällig ausgewählt, um in die Analyse einbezogen zu werden. Aufgrund fehlender Daten für das Jahr 2023 konnte die Landeshauptstadt von Mecklenburg-Vorpommern, Schwerin, nicht in die Analyse einbezogen werden. Um eine Vertretung für Mecklenburg-Vorpommern sicherzustellen, wurde Rostock, die größte und bevölkerungsreichste Stadt des Bundeslandes, als Ersatz herangezogen.</p>
<p>Bei OpenAg konnten maximal 1000 Aufzeichnungen pro Parameter gleichzeitig heruntergeladen werden. Die Stadtdaten wurden in Etappen heruntergeladen und entsprechend beschriftet. Sie liegen im CSV-Datenformat vor und sind in Excel-Tabellen gespeichert. Zusätzlich wurde eine Deutschlandkarte heruntergeladen. Die Rohdaten enthalten Messungen der PM<sub>2,5</sub>-Konzentrationen, Datums- und Zeitstempel der Messungen, geografische Koordinaten (Breitengrad und Längengrad) der Messstationen sowie Metadaten wie Landescode, Stationstyp (mobil oder stationär) und den Namen des Datenanbieters.</p>
<p>Die Datenanalyse wurde mithilfe der Software R (Version: R. 4.3.3) durchgeführt. Dabei wurden spezifische Pakete für statistische Berechnungen und räumliche Analysen verwendet. Bei der Datenerhebung gab es Herausforderungen, wie beispielsweise die Begrenzung der Datenverfügbarkeit auf bestimmte Zeiträume und Standorte sowie die Notwendigkeit, Datenlücken durch Interpolation zu füllen.</p>
<p>Die Datenreinigung und -aufbereitung umfasste die Prüfung auf Vollständigkeit, die Interpolation fehlender Werte und die Anpassung an saisonale Analysezeitfenster. Im Sommer wurden die Monate Mai und Juni betrachtet, im Winter November und Dezember. Anschließend wurde eine saisonale Clusteranalyse durchgeführt, um Muster in den PM<sub>2.5</sub>-Konzentrationen zu erkennen und potenzielle Zusammenhänge mit städtischen Merkmalen wie der Einwohnerzahl zu untersuchen.</p>
<p>Die Analysemethoden umfassten deskriptive Statistiken, räumliche Visualisierungen und statistische Modellierung, einschließlich Cluster- und Korrelationsanalysen, die in R durchgeführt wurden. Die Interpretation der Ergebnisse berücksichtigt die Einschränkungen der Datenverfügbarkeit, die Auswahl der Messstationen und die angewandten Analysemethoden. Dadurch können zuverlässige Schlussfolgerungen über die Luftqualität und ihre Determinanten in den untersuchten urbanen Gebieten gezogen werden.</p>
</div>
<div id="packages-und-working-directory" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Packages und Working Directory<a href="methodik.html#packages-und-working-directory" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Es wurden folgende Pakete verwendet, welche eine umfassende Bearbeitung und Visualisierung der Luftqualitätsdaten ermöglichen.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="methodik.html#cb42-1" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(shiny)) {<span class="fu">install.packages</span>(<span class="st">&quot;shiny&quot;</span>); <span class="fu">library</span>(shiny)}</span>
<span id="cb42-2"><a href="methodik.html#cb42-2" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(plotly)) {<span class="fu">install.packages</span>(<span class="st">&quot;plotly&quot;</span>); <span class="fu">library</span>(plotly)}</span>
<span id="cb42-3"><a href="methodik.html#cb42-3" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(leaflet)) {<span class="fu">install.packages</span>(<span class="st">&quot;leaflet&quot;</span>); <span class="fu">library</span>(leaflet)}</span>
<span id="cb42-4"><a href="methodik.html#cb42-4" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(tidyverse)) {<span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>); <span class="fu">library</span>(tidyverse)}</span>
<span id="cb42-5"><a href="methodik.html#cb42-5" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(dplyr)) {<span class="fu">install.packages</span>(<span class="st">&quot;dplyr&quot;</span>); <span class="fu">library</span>(dplyr)}</span>
<span id="cb42-6"><a href="methodik.html#cb42-6" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(lubridate)) {<span class="fu">install.packages</span>(<span class="st">&quot;lubridate&quot;</span>); <span class="fu">library</span>(lubridate)}</span>
<span id="cb42-7"><a href="methodik.html#cb42-7" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(readxl)) {<span class="fu">install.packages</span>(<span class="st">&quot;readxl&quot;</span>); <span class="fu">library</span>(readxl)}</span>
<span id="cb42-8"><a href="methodik.html#cb42-8" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(readr)) {<span class="fu">install.packages</span>(<span class="st">&quot;readr&quot;</span>); <span class="fu">library</span>(readr)}</span>
<span id="cb42-9"><a href="methodik.html#cb42-9" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(imputeTS)) {<span class="fu">install.packages</span>(<span class="st">&quot;imputeTS&quot;</span>); <span class="fu">library</span>(imputeTS)}</span>
<span id="cb42-10"><a href="methodik.html#cb42-10" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(sf)) {<span class="fu">install.packages</span>(<span class="st">&quot;sf&quot;</span>); <span class="fu">library</span>(sf)}</span>
<span id="cb42-11"><a href="methodik.html#cb42-11" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(tinytex)) {<span class="fu">install.packages</span>(<span class="st">&quot;tinytex&quot;</span>); <span class="fu">library</span>(tinytex)}</span>
<span id="cb42-12"><a href="methodik.html#cb42-12" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(downlit)) {<span class="fu">install.packages</span>(<span class="st">&quot;downlit&quot;</span>); <span class="fu">library</span>(downlit)}</span>
<span id="cb42-13"><a href="methodik.html#cb42-13" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(viridis)) {<span class="fu">install.packages</span>(<span class="st">&quot;viridis&quot;</span>); <span class="fu">library</span>(viridis)}</span>
<span id="cb42-14"><a href="methodik.html#cb42-14" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(bookdown)) {<span class="fu">install.packages</span>(<span class="st">&quot;bookdown&quot;</span>); <span class="fu">library</span>(bookdown)}</span></code></pre></div>
</div>
<div id="datenbereinigung" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Datenbereinigung<a href="methodik.html#datenbereinigung" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Die Daten wurden in R-Studio geladen. Anschließend wurden die Datensätze mithilfe von “data_list” in einen gemeinsamen Dataframe überführt und mit “bind_rows” zu einem übersichtlichen und geordneten Dataframe zusammengeführt.
Die Liste “cities_raw_names” speichert die Namen der Rohdatensätze für jede Stadt. In der Funktion “process_city_data” werden die Daten bereinigt, indem Duplikate entfernt, Zeitstempel in Datum und Uhrzeit segmentiert und irrelevante Spalten gelöscht werden. Da die ursprünglichen Daten Mitternachtsmessungen um 00:00:00 enthielten, wurden diese jedoch während des Aufbereitungsprozesses entfernt. Die Funktion fügt diese Messungen systematisch wieder ein, um eine vollständige und konsistente Datenbasis zu gewährleisten. Die aufbereiteten Daten werden für jede Stadt in der globalen Umgebung gespeichert, um eine einheitliche Basis für die nächtlichen Zeitpunktanalysen zu schaffen.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="methodik.html#cb43-1" tabindex="-1"></a>cities_raw_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Berlin_raw&quot;</span>, <span class="st">&quot;Bremen_raw&quot;</span>, <span class="st">&quot;Dresden_raw&quot;</span>, <span class="st">&quot;Düsseldorf_raw&quot;</span>, </span>
<span id="cb43-2"><a href="methodik.html#cb43-2" tabindex="-1"></a>                      <span class="st">&quot;Erfurt_raw&quot;</span>, <span class="st">&quot;Hamburg_raw&quot;</span>, <span class="st">&quot;Hannover_raw&quot;</span>, <span class="st">&quot;Kiel_raw&quot;</span>, </span>
<span id="cb43-3"><a href="methodik.html#cb43-3" tabindex="-1"></a>                      <span class="st">&quot;Magdeburg_raw&quot;</span>, <span class="st">&quot;Mainz_raw&quot;</span>, <span class="st">&quot;München_raw&quot;</span>, <span class="st">&quot;Potsdam_raw&quot;</span>, </span>
<span id="cb43-4"><a href="methodik.html#cb43-4" tabindex="-1"></a>                      <span class="st">&quot;Rostock_raw&quot;</span>, <span class="st">&quot;Saarbrücken_raw&quot;</span>, <span class="st">&quot;Stuttgart_raw&quot;</span>, <span class="st">&quot;Wiesbaden_raw&quot;</span>)</span>
<span id="cb43-5"><a href="methodik.html#cb43-5" tabindex="-1"></a></span>
<span id="cb43-6"><a href="methodik.html#cb43-6" tabindex="-1"></a>cities_names <span class="ot">&lt;-</span> <span class="fu">sub</span>(<span class="st">&quot;_raw$&quot;</span>, <span class="st">&quot;&quot;</span>, cities_raw_names)</span>
<span id="cb43-7"><a href="methodik.html#cb43-7" tabindex="-1"></a>process_city_data <span class="ot">&lt;-</span> <span class="cf">function</span>(city_raw, city_name) {</span>
<span id="cb43-8"><a href="methodik.html#cb43-8" tabindex="-1"></a>  city_raw <span class="sc">%&gt;%</span></span>
<span id="cb43-9"><a href="methodik.html#cb43-9" tabindex="-1"></a>    <span class="fu">distinct</span>(datetimeLocal, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-10"><a href="methodik.html#cb43-10" tabindex="-1"></a>    <span class="fu">separate</span>(datetimeLocal, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;date&quot;</span>, <span class="st">&quot;time&quot;</span>), <span class="at">sep =</span> <span class="st">&quot; &quot;</span>, <span class="at">fill =</span> <span class="st">&quot;right&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-11"><a href="methodik.html#cb43-11" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">time =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(time), <span class="st">&quot;00:00:00&quot;</span>, time)) <span class="sc">%&gt;%</span></span>
<span id="cb43-12"><a href="methodik.html#cb43-12" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>timezone, <span class="sc">-</span>datetimeUtc, <span class="sc">-</span>country_iso, <span class="sc">-</span>isMobile, <span class="sc">-</span>isMonitor) <span class="sc">%&gt;%</span></span>
<span id="cb43-13"><a href="methodik.html#cb43-13" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">location_name =</span> city_name)</span>
<span id="cb43-14"><a href="methodik.html#cb43-14" tabindex="-1"></a>}</span>
<span id="cb43-15"><a href="methodik.html#cb43-15" tabindex="-1"></a></span>
<span id="cb43-16"><a href="methodik.html#cb43-16" tabindex="-1"></a></span>
<span id="cb43-17"><a href="methodik.html#cb43-17" tabindex="-1"></a><span class="cf">for</span> (city <span class="cf">in</span> cities_names) {</span>
<span id="cb43-18"><a href="methodik.html#cb43-18" tabindex="-1"></a>  city_raw_var_name <span class="ot">&lt;-</span> <span class="fu">paste0</span>(city, <span class="st">&quot;_raw&quot;</span>)</span>
<span id="cb43-19"><a href="methodik.html#cb43-19" tabindex="-1"></a>  </span>
<span id="cb43-20"><a href="methodik.html#cb43-20" tabindex="-1"></a>  </span>
<span id="cb43-21"><a href="methodik.html#cb43-21" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">exists</span>(city_raw_var_name, <span class="at">envir =</span> .GlobalEnv)) {</span>
<span id="cb43-22"><a href="methodik.html#cb43-22" tabindex="-1"></a>    city_raw <span class="ot">&lt;-</span> <span class="fu">get</span>(city_raw_var_name, <span class="at">envir =</span> .GlobalEnv)</span>
<span id="cb43-23"><a href="methodik.html#cb43-23" tabindex="-1"></a>    city_cleaned <span class="ot">&lt;-</span> <span class="fu">process_city_data</span>(city_raw, city)</span>
<span id="cb43-24"><a href="methodik.html#cb43-24" tabindex="-1"></a>    </span>
<span id="cb43-25"><a href="methodik.html#cb43-25" tabindex="-1"></a>    <span class="co"># Überschreiben der alten Rohdaten mit den bereinigten Daten im Global Environment</span></span>
<span id="cb43-26"><a href="methodik.html#cb43-26" tabindex="-1"></a>    <span class="fu">assign</span>(city, city_cleaned, <span class="at">envir =</span> .GlobalEnv)</span>
<span id="cb43-27"><a href="methodik.html#cb43-27" tabindex="-1"></a>  }</span>
<span id="cb43-28"><a href="methodik.html#cb43-28" tabindex="-1"></a>}</span></code></pre></div>
</div>
<div id="datenüberprüfung-auf-vollständigkeit" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Datenüberprüfung auf Vollständigkeit<a href="methodik.html#datenüberprüfung-auf-vollständigkeit" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Um zu überprüfen, ob der Datensatz vollständig ist bezüglich der Messtage, wurde untersucht, an wie vielen Tagen die Städte jeweils Messungen durchgeführt haben. Dazu wurde die Funktion sapply() verwendet, um für jede Stadt die eindeutigen Messdaten (Tage) zu ermitteln. Hierfür wurde der Befehl unique(city_data$date) genutzt, der die Anzahl der einzigartigen Messdaten in jedem Stadtdatensatz zählte. Die Funktion get(city) ruft dynamisch den entsprechenden Datensatz für jede Stadt ab. Das Ergebnis, num_days_per_city, enthält die Anzahl der Messdaten pro Stadt für das Jahr 2023.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="methodik.html#cb44-1" tabindex="-1"></a>cities_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Berlin&quot;</span>, <span class="st">&quot;Bremen&quot;</span>, <span class="st">&quot;Dresden&quot;</span>, <span class="st">&quot;Düsseldorf&quot;</span>, <span class="st">&quot;Erfurt&quot;</span>, <span class="st">&quot;Hamburg&quot;</span>, <span class="st">&quot;Hannover&quot;</span>, </span>
<span id="cb44-2"><a href="methodik.html#cb44-2" tabindex="-1"></a>                  <span class="st">&quot;Kiel&quot;</span>, <span class="st">&quot;Magdeburg&quot;</span>, <span class="st">&quot;Mainz&quot;</span>, <span class="st">&quot;München&quot;</span>, <span class="st">&quot;Potsdam&quot;</span>, <span class="st">&quot;Saarbrücken&quot;</span>, </span>
<span id="cb44-3"><a href="methodik.html#cb44-3" tabindex="-1"></a>                  <span class="st">&quot;Rostock&quot;</span>, <span class="st">&quot;Stuttgart&quot;</span>, <span class="st">&quot;Wiesbaden&quot;</span>)</span>
<span id="cb44-4"><a href="methodik.html#cb44-4" tabindex="-1"></a></span>
<span id="cb44-5"><a href="methodik.html#cb44-5" tabindex="-1"></a><span class="co"># Anzahl der Messtage pro Stadt im Jahr 2023 zählen</span></span>
<span id="cb44-6"><a href="methodik.html#cb44-6" tabindex="-1"></a>num_days_per_city <span class="ot">&lt;-</span> <span class="fu">sapply</span>(cities_names, <span class="cf">function</span>(city) {</span>
<span id="cb44-7"><a href="methodik.html#cb44-7" tabindex="-1"></a>  city_data <span class="ot">&lt;-</span> <span class="fu">get</span>(city)</span>
<span id="cb44-8"><a href="methodik.html#cb44-8" tabindex="-1"></a>  <span class="fu">length</span>(<span class="fu">unique</span>(city_data<span class="sc">$</span>date))</span>
<span id="cb44-9"><a href="methodik.html#cb44-9" tabindex="-1"></a>})</span>
<span id="cb44-10"><a href="methodik.html#cb44-10" tabindex="-1"></a><span class="fu">print</span>(num_days_per_city)</span></code></pre></div>
<pre><code>##      Berlin      Bremen     Dresden  Düsseldorf      Erfurt     Hamburg 
##         305         307         205         206         224         221 
##    Hannover        Kiel   Magdeburg       Mainz     München     Potsdam 
##         311         310         217         207         308         157 
## Saarbrücken     Rostock   Stuttgart   Wiesbaden 
##         207         216         215         217</code></pre>
<p>Die Analyse der Daten zeigt, dass die Anzahl der Messungen pro Stadt im Jahr 2023 stark variierte. Keine Stadt verfügt über einen vollständigen Datensatz, jedoch variierte die Anzahl der Messtage stark. Hannover hat beispielsweise mit 311 Messungstagen die meisten Messungen durchgeführt, während Potsdam nur 157 Tage mit Messungen verzeichnete. Diese Inkonsistenz in den Datenpunkten verdeutlicht die Notwendigkeit einer detaillierten Untersuchung der Messzeitpunkte, um eine fundierte Vergleichsbasis zu schaffen.</p>
</div>
<div id="ermittlung-der-häufigsten-messzeiten-und-auswahl-des-analysezeitraums" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Ermittlung der häufigsten Messzeiten und Auswahl des Analysezeitraums<a href="methodik.html#ermittlung-der-häufigsten-messzeiten-und-auswahl-des-analysezeitraums" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Um die Vergleichbarkeit zu verbessern, wurde eine Analyse der häufigsten Messzeiten in jeder Stadt durchgeführt. Das Ziel dieses Schrittes ist es, den spezifischen Zeitpunkt zu identifizieren, zu dem die meisten Messungen durchgeführt wurden. Mithilfe der Funktion lapply() wurde für jede Stadt die am häufigsten vorkommende Messzeit ermittelt. Durch die Gruppierung der Daten nach der Zeit und der Berechnung der Frequenz jeder Messung konnte für jede Stadt die Zeit mit der höchsten Messfrequenz ermittelt werden.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="methodik.html#cb46-1" tabindex="-1"></a><span class="co"># Häufigste Messzeiten für jede Stadt bestimmen</span></span>
<span id="cb46-2"><a href="methodik.html#cb46-2" tabindex="-1"></a>most_common_times <span class="ot">&lt;-</span> <span class="fu">lapply</span>(cities_names, <span class="cf">function</span>(city_name) {</span>
<span id="cb46-3"><a href="methodik.html#cb46-3" tabindex="-1"></a>  city_data <span class="ot">&lt;-</span> <span class="fu">get</span>(city_name)</span>
<span id="cb46-4"><a href="methodik.html#cb46-4" tabindex="-1"></a>  time_freq <span class="ot">&lt;-</span> city_data <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="methodik.html#cb46-5" tabindex="-1"></a>    <span class="fu">group_by</span>(time) <span class="sc">%&gt;%</span></span>
<span id="cb46-6"><a href="methodik.html#cb46-6" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">freq =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb46-7"><a href="methodik.html#cb46-7" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(freq)) <span class="sc">%&gt;%</span></span>
<span id="cb46-8"><a href="methodik.html#cb46-8" tabindex="-1"></a>    <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-9"><a href="methodik.html#cb46-9" tabindex="-1"></a>    <span class="fu">ungroup</span>()</span>
<span id="cb46-10"><a href="methodik.html#cb46-10" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">city =</span> city_name, <span class="at">time =</span> time_freq<span class="sc">$</span>time, <span class="at">freq =</span> time_freq<span class="sc">$</span>freq)</span>
<span id="cb46-11"><a href="methodik.html#cb46-11" tabindex="-1"></a>})</span>
<span id="cb46-12"><a href="methodik.html#cb46-12" tabindex="-1"></a></span>
<span id="cb46-13"><a href="methodik.html#cb46-13" tabindex="-1"></a><span class="co"># Kombiniert die Ergebnisse in einem Dataframe</span></span>
<span id="cb46-14"><a href="methodik.html#cb46-14" tabindex="-1"></a>most_common_times_df <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, most_common_times)</span>
<span id="cb46-15"><a href="methodik.html#cb46-15" tabindex="-1"></a><span class="fu">print</span>(most_common_times_df)</span></code></pre></div>
<pre><code>##       city          time       freq 
##  [1,] &quot;Berlin&quot;      &quot;01:00:00&quot; &quot;293&quot;
##  [2,] &quot;Bremen&quot;      &quot;01:00:00&quot; &quot;293&quot;
##  [3,] &quot;Dresden&quot;     &quot;00:00:00&quot; &quot;194&quot;
##  [4,] &quot;Düsseldorf&quot;  &quot;00:00:00&quot; &quot;197&quot;
##  [5,] &quot;Erfurt&quot;      &quot;00:00:00&quot; &quot;216&quot;
##  [6,] &quot;Hamburg&quot;     &quot;00:00:00&quot; &quot;212&quot;
##  [7,] &quot;Hannover&quot;    &quot;00:00:00&quot; &quot;303&quot;
##  [8,] &quot;Kiel&quot;        &quot;00:00:00&quot; &quot;300&quot;
##  [9,] &quot;Magdeburg&quot;   &quot;00:00:00&quot; &quot;208&quot;
## [10,] &quot;Mainz&quot;       &quot;00:00:00&quot; &quot;196&quot;
## [11,] &quot;München&quot;     &quot;00:00:00&quot; &quot;300&quot;
## [12,] &quot;Potsdam&quot;     &quot;00:00:00&quot; &quot;156&quot;
## [13,] &quot;Saarbrücken&quot; &quot;00:00:00&quot; &quot;197&quot;
## [14,] &quot;Rostock&quot;     &quot;00:00:00&quot; &quot;207&quot;
## [15,] &quot;Stuttgart&quot;   &quot;00:00:00&quot; &quot;207&quot;
## [16,] &quot;Wiesbaden&quot;   &quot;00:00:00&quot; &quot;209&quot;</code></pre>
<p>Bei der Analyse der häufigsten Messzeiten in jeder Stadt zeigt sich, dass in 14 der 16 untersuchten Städte die Messungen um Mitternacht (00:00:00 Uhr) stattfanden. Lediglich in Berlin und Bremen wurden die Messungen eine Stunde später, um 01:00:00 Uhr, durchgeführt. Die Häufigkeit der Messungen um Mitternacht unterstreicht die Relevanz dieses Zeitpunktes für die Datenerhebung und -auswertung. Aus diesem Grund wurden die Mitternachtsdaten als Hauptzeitpunkt für die Analyse ausgewählt. Es wird angenommen, dass Mitternachtsmessungen die tägliche Luftqualität am besten widerspiegeln, da zu dieser Zeit weniger Verkehr und Spitzenwerte auftreten, die das Ergebnis verfälschen könnten. Außerdem bieten Mitternachtsmessungen einen einheitlichen Vergleichsmaßstab über alle Städte hinweg.</p>
<p>Die Funktion ‘process_city_data’ wurde verwendet, um die Daten für jede Stadt zu verarbeiten. Dabei lag der Schwerpunkt auf den Mitternachtsmessungen. Diese Funktion standardisiert die Zeitangaben, berechnet tägliche Durchschnittswerte und isoliert die Mitternachtsdaten. Dadurch wird eine konsistente Datenbasis für die weiterführende Analyse geschaffen. Die Datensätze all_cities_daily_avg und all_cities_midnight bieten eine umfassende Sicht auf die Luftqualität in den untersuchten Städten. Sie enthalten Informationen sowohl für den täglichen Durchschnitt als auch für den Mitternachtszeitpunkt.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="methodik.html#cb48-1" tabindex="-1"></a><span class="co"># Funktion zur Datenverarbeitung für jede Stadt</span></span>
<span id="cb48-2"><a href="methodik.html#cb48-2" tabindex="-1"></a>process_city_data <span class="ot">&lt;-</span> <span class="cf">function</span>(city_name, <span class="at">filter_time =</span> <span class="st">&quot;00:00:00&quot;</span>) {</span>
<span id="cb48-3"><a href="methodik.html#cb48-3" tabindex="-1"></a>  city_data <span class="ot">&lt;-</span> <span class="fu">get</span>(city_name, <span class="at">envir =</span> .GlobalEnv)</span>
<span id="cb48-4"><a href="methodik.html#cb48-4" tabindex="-1"></a>  extra_cols <span class="ot">&lt;-</span> city_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(longitude, latitude, unit) <span class="sc">%&gt;%</span> <span class="fu">distinct</span>()</span>
<span id="cb48-5"><a href="methodik.html#cb48-5" tabindex="-1"></a>  </span>
<span id="cb48-6"><a href="methodik.html#cb48-6" tabindex="-1"></a>  city_data <span class="ot">&lt;-</span> city_data <span class="sc">%&gt;%</span></span>
<span id="cb48-7"><a href="methodik.html#cb48-7" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.Date</span>(date)) <span class="sc">%&gt;%</span></span>
<span id="cb48-8"><a href="methodik.html#cb48-8" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">time =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(time), filter_time, time))</span>
<span id="cb48-9"><a href="methodik.html#cb48-9" tabindex="-1"></a>  </span>
<span id="cb48-10"><a href="methodik.html#cb48-10" tabindex="-1"></a>  daily_avg <span class="ot">&lt;-</span> city_data <span class="sc">%&gt;%</span></span>
<span id="cb48-11"><a href="methodik.html#cb48-11" tabindex="-1"></a>    <span class="fu">group_by</span>(date) <span class="sc">%&gt;%</span></span>
<span id="cb48-12"><a href="methodik.html#cb48-12" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">value_daily_avg =</span> <span class="fu">mean</span>(value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb48-13"><a href="methodik.html#cb48-13" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">location_name =</span> city_name) <span class="sc">%&gt;%</span></span>
<span id="cb48-14"><a href="methodik.html#cb48-14" tabindex="-1"></a>    <span class="fu">cross_join</span>(extra_cols)</span>
<span id="cb48-15"><a href="methodik.html#cb48-15" tabindex="-1"></a>  </span>
<span id="cb48-16"><a href="methodik.html#cb48-16" tabindex="-1"></a>  midnight_data <span class="ot">&lt;-</span> city_data <span class="sc">%&gt;%</span></span>
<span id="cb48-17"><a href="methodik.html#cb48-17" tabindex="-1"></a>    <span class="fu">filter</span>(time <span class="sc">==</span> filter_time) <span class="sc">%&gt;%</span></span>
<span id="cb48-18"><a href="methodik.html#cb48-18" tabindex="-1"></a>    <span class="fu">group_by</span>(date) <span class="sc">%&gt;%</span></span>
<span id="cb48-19"><a href="methodik.html#cb48-19" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">value_midnight =</span> <span class="fu">mean</span>(value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb48-20"><a href="methodik.html#cb48-20" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">location_name =</span> city_name) <span class="sc">%&gt;%</span></span>
<span id="cb48-21"><a href="methodik.html#cb48-21" tabindex="-1"></a>    <span class="fu">cross_join</span>(extra_cols)</span>
<span id="cb48-22"><a href="methodik.html#cb48-22" tabindex="-1"></a>  </span>
<span id="cb48-23"><a href="methodik.html#cb48-23" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">daily_avg =</span> daily_avg, <span class="at">midnight_data =</span> midnight_data)</span>
<span id="cb48-24"><a href="methodik.html#cb48-24" tabindex="-1"></a>}</span>
<span id="cb48-25"><a href="methodik.html#cb48-25" tabindex="-1"></a></span>
<span id="cb48-26"><a href="methodik.html#cb48-26" tabindex="-1"></a><span class="co"># Verarbeitet die Daten für jede Stadt, um tägliche Durchschnittswerte und Mitternachtsdaten zu erhalten</span></span>
<span id="cb48-27"><a href="methodik.html#cb48-27" tabindex="-1"></a>processed_city_data <span class="ot">&lt;-</span> <span class="fu">lapply</span>(cities_names, process_city_data)</span>
<span id="cb48-28"><a href="methodik.html#cb48-28" tabindex="-1"></a></span>
<span id="cb48-29"><a href="methodik.html#cb48-29" tabindex="-1"></a><span class="co"># Kombiniert tägliche Durchschnitts- und Mitternachtsdaten für alle Städte</span></span>
<span id="cb48-30"><a href="methodik.html#cb48-30" tabindex="-1"></a>all_cities_daily_avg <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(processed_city_data, <span class="st">`</span><span class="at">[[</span><span class="st">`</span>, <span class="st">&quot;daily_avg&quot;</span>), <span class="at">.id =</span> <span class="st">&quot;city&quot;</span>)</span>
<span id="cb48-31"><a href="methodik.html#cb48-31" tabindex="-1"></a>all_cities_midnight <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(processed_city_data, <span class="st">`</span><span class="at">[[</span><span class="st">`</span>, <span class="st">&quot;midnight_data&quot;</span>), <span class="at">.id =</span> <span class="st">&quot;city&quot;</span>)</span>
<span id="cb48-32"><a href="methodik.html#cb48-32" tabindex="-1"></a></span>
<span id="cb48-33"><a href="methodik.html#cb48-33" tabindex="-1"></a><span class="co"># Kombinieren der täglichen Durchschnitts- und Mitternachtsdaten für alle Städte in einem Dataframe</span></span>
<span id="cb48-34"><a href="methodik.html#cb48-34" tabindex="-1"></a>all_cities_data <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(all_cities_daily_avg, all_cities_midnight)</span>
<span id="cb48-35"><a href="methodik.html#cb48-35" tabindex="-1"></a></span>
<span id="cb48-36"><a href="methodik.html#cb48-36" tabindex="-1"></a><span class="do">## Analysiert die monatliche Datenabdeckung</span></span>
<span id="cb48-37"><a href="methodik.html#cb48-37" tabindex="-1"></a>dates_monthly <span class="ot">&lt;-</span> all_cities_data <span class="sc">%&gt;%</span></span>
<span id="cb48-38"><a href="methodik.html#cb48-38" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="at">Jahr =</span> <span class="fu">year</span>(date), <span class="at">Monat =</span> <span class="fu">month</span>(date)) <span class="sc">%&gt;%</span></span>
<span id="cb48-39"><a href="methodik.html#cb48-39" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb48-40"><a href="methodik.html#cb48-40" tabindex="-1"></a>    Verfügbare<span class="at">_Tage =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(value_daily_avg), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb48-41"><a href="methodik.html#cb48-41" tabindex="-1"></a>    Verfügbare<span class="at">_Tage_Mitternacht =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(value_midnight), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb48-42"><a href="methodik.html#cb48-42" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span></span>
<span id="cb48-43"><a href="methodik.html#cb48-43" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb48-44"><a href="methodik.html#cb48-44" tabindex="-1"></a>  <span class="co"># Füge eine neue Spalte hinzu, die die Differenz der verfügbaren Tage zeigt</span></span>
<span id="cb48-45"><a href="methodik.html#cb48-45" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Differenz =</span> Verfügbare_Tage <span class="sc">-</span> Verfügbare_Tage_Mitternacht) <span class="sc">%&gt;%</span></span>
<span id="cb48-46"><a href="methodik.html#cb48-46" tabindex="-1"></a>  <span class="co"># Benenne die Spalten um für eine klarere Darstellung</span></span>
<span id="cb48-47"><a href="methodik.html#cb48-47" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">&quot;Verfügbare Tage&quot;</span> <span class="ot">=</span> Verfügbare_Tage,</span>
<span id="cb48-48"><a href="methodik.html#cb48-48" tabindex="-1"></a>         <span class="st">&quot;Verfügbare Tage Mitternacht&quot;</span> <span class="ot">=</span> Verfügbare_Tage_Mitternacht,</span>
<span id="cb48-49"><a href="methodik.html#cb48-49" tabindex="-1"></a>         <span class="st">&quot;Differenz&quot;</span> <span class="ot">=</span> Differenz)</span>
<span id="cb48-50"><a href="methodik.html#cb48-50" tabindex="-1"></a></span>
<span id="cb48-51"><a href="methodik.html#cb48-51" tabindex="-1"></a><span class="fu">print</span>(dates_monthly)</span></code></pre></div>
<pre><code>## # A tibble: 12 × 5
##     Jahr Monat `Verfügbare Tage` `Verfügbare Tage Mitternacht` Differenz
##    &lt;dbl&gt; &lt;dbl&gt;             &lt;int&gt;                         &lt;int&gt;     &lt;int&gt;
##  1  2023     1               267                           255        12
##  2  2023     2                75                            51        24
##  3  2023     3               195                           150        45
##  4  2023     4               434                           401        33
##  5  2023     5               494                           490         4
##  6  2023     6               480                           477         3
##  7  2023     7               304                           301         3
##  8  2023     8               142                           142         0
##  9  2023     9               218                           216         2
## 10  2023    10               254                           239        15
## 11  2023    11               479                           475         4
## 12  2023    12               491                           487         4</code></pre>
<p>Es werden Heatmaps erstellt, welche die verfügbaren Tage anzeigen.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="methodik.html#cb50-1" tabindex="-1"></a><span class="fu">print</span>(heatmap_daily_avg)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="methodik.html#cb51-1" tabindex="-1"></a><span class="fu">print</span>(heatmap_midnight)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-7-2.png" width="672" />
Die Tabelle vergleicht die Anzahl der Tage pro Monat, an denen PM<sub>2.5</sub>-Daten erfasst wurden, mit den Messungen, die exakt um Mitternacht durchgeführt wurden. Besonders wichtig ist die Differenz-Spalte, da sie Aufschluss über die Übereinstimmung der Datenerhebung zu diesem Zeitpunkt gibt. Die Monate Mai bis Juni sowie November bis Dezember weisen eine hohe Übereinstimmung mit Differenzen von maximal vier Tagen auf. Dies deutet auf eine nahezu lückenlose Datenerfassung in diesen Zeiträumen hin.
Daher eignen sich diese Monate besonders für eine Vergleichsanalyse, da eine hohe Datenverfügbarkeit die Zuverlässigkeit der Untersuchungsergebnisse unterstützt. Im Gegensatz dazu zeigen die Monate Februar und März größere Differenzen. Möglicherweise deuten diese auf inkonsistente Datenerhebungszeiten oder fehlende Daten hin.
Die Entscheidung, Mitternacht als gemeinsamen Zeitpunkt für die Analyse zu wählen, basiert auf der hohen Datenverfügbarkeit in den vorhandenen Monaten und der Notwendigkeit, einen standardisierten und reproduzierbaren Analyseansatz zu verfolgen. Die Heatmaps zeigen deutlich, dass in diesen Monaten die Datenlücken minimal sind, während in anderen Monaten wie Februar und März signifikante Inkonsistenzen bestehen.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="einleitung.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="analyse.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/Methodik.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
